INSERT INTO sport_sport (show, name) VALUES ('Бадминтон', 'Badminton');
INSERT INTO sport_sport (show, name) VALUES ('Баскетбол', 'Basketball');
INSERT INTO sport_sport (show, name) VALUES ('Бейсбол', 'Baseball');
INSERT INTO sport_sport (show, name) VALUES ('Волейбол', 'Volleyball');
INSERT INTO sport_sport (show, name) VALUES ('Водное поло', 'Water Polo');
INSERT INTO sport_sport (show, name) VALUES ('Гандбол', 'Handball');
INSERT INTO sport_sport (show, name) VALUES ('Гольф', 'Golf');
INSERT INTO sport_sport (show, name) VALUES ('Городки', 'Towns');
INSERT INTO sport_sport (show, name) VALUES ('Корфбол', 'Korfball');
INSERT INTO sport_sport (show, name) VALUES ('Мини водное поло', 'Mini water polo');
INSERT INTO sport_sport (show, name) VALUES ('Мини-футбол', 'Mini Football');
INSERT INTO sport_sport (show, name) VALUES ('Настольный теннис', 'Table Tennis');
INSERT INTO sport_sport (show, name) VALUES ('Настольный футбол', 'Table football');
INSERT INTO sport_sport (show, name) VALUES ('Регби', 'Rugby');
INSERT INTO sport_sport (show, name) VALUES ('Спидминтон', 'Speedminton');
INSERT INTO sport_sport (show, name) VALUES ('Теннис', 'Tennis');
INSERT INTO sport_sport (show, name) VALUES ('Футбол', 'Football');
INSERT INTO sport_sport (show, name) VALUES ('Футзал', 'Futsal');
INSERT INTO sport_sport (show, name) VALUES ('Хоккей', 'Hockey');